### ISSUE TITLE
通达oa 组合拳getshell

### ISSUE THREAD

**Issue by LuoooB** [Liqunkit/LiqunKit_#16]
RT
能确定网站存在漏洞，并且手工能弹出来，但是用工具没成功。

**Comment by Liqunkit** [comment]
具体是你那个漏洞提供下，有时间改下

**Comment by LuoooB** [comment]
组合拳  上传加解压getshell



***@***.***
 
发件人： Liqun
发送时间： 2021-12-27 09:17
收件人： Liqunkit/LiqunKit_
抄送： June; Author
主题： Re: [Liqunkit/LiqunKit_] 通达oa 组合拳getshell (Issue #16)
具体是你那个漏洞提供下，有时间改下
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
