### ISSUE TITLE
1.4版本闪退

### ISSUE THREAD

**Issue by Xu1Z** [Liqunkit/LiqunKit_#2]
m1 java11.0.11闪退，打开然后生成了shell.txt就没了。

**Comment by snowlovely** [comment]
> m1 java11.0.11闪退，打开然后生成了shell.txt就没了。

这个项目是用java 8 写的，请使用 java 8运行
另外该jar包名字因为加密缘故不能修改，修改后会无法打开

**Comment by LycsHub** [comment]
ubuntu 20.04打开没反映，也生成了shell.txt，截图如下
![](https://gitee.com/tjdx1817054/typora/raw/master/1636515166558-2021-11-1011:32:46.png)
