### ISSUE TITLE
卧槽

### ISSUE THREAD

**Issue by CtrlAltDelet** [Liqunkit/LiqunKit_#4]
![image](https://user-images.githubusercontent.com/38282439/143667268-d14db7c8-b11e-48ea-b35a-8b7151fb2c56.png)

**Comment by CtrlAltDelet** [comment]
java8 之前版本可以正常打开 新的版本提示未响应

**Comment by GTX8090TI** [comment]
用jdk8 运行就好了

**Comment by kuaiyulong** [comment]
大佬们  你们咋打开的  我的都没出界面哇

**Comment by CtrlAltDelet** [comment]
> 

不能重命名

**Comment by kuainima** [comment]
是直接解压出来的  没有重命名
