### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by yangyang1144** [Liqunkit/LiqunKit_#5]
双击直接就无法运行 应该怎样运行呢  java17   java16 java1.8.0都安着了 就是不行啊
![image](https://user-images.githubusercontent.com/83336628/143907215-5343f863-2594-4081-a6cb-ea61a251ffcb.png)

**Comment by Liqunkit** [comment]
javaw -jar LiqunKit_1.5.jar  试试看

**Comment by wooluo** [comment]
macos 下，先找到echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home

#/bin/bash
cd /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/bin
./java -jar /Users/zl/tools/LiqunKit_1.5/LiqunKit_1.5.jar
保存成sh文件，启动就可以了

**Comment by yangyang1144** [comment]
还是不行啊  javaw -jar LiqunKit_1.5.jar没反应 
![image](https://user-images.githubusercontent.com/83336628/144058046-f5a39d00-0bd7-4515-93ad-77db2098dac1.png)
kali也不行
![image](https://user-images.githubusercontent.com/83336628/144058235-0fa0a3a5-27f0-48b7-af0d-2a47b8c0289d.png)

**Comment by apsry** [comment]
> 还是不行啊 javaw -jar LiqunKit_1.5.jar没反应 ![image](https://user-images.githubusercontent.com/83336628/144058046-f5a39d00-0bd7-4515-93ad-77db2098dac1.png) kali也不行 ![image](https://user-images.githubusercontent.com/83336628/144058235-0fa0a3a5-27f0-48b7-af0d-2a47b8c0289d.png)

用shell写一个启动就可以了 java8可用，不要改名字，java -jar 即可

**Comment by Liqunkit** [comment]
可能是受到到加密的影响所以部分环境启动有问题，明天更新下加密方式应该就会好很多

**Comment by DroidKali** [comment]
一样的情况，看来作者还没修复吧
![](https://ftp.bmp.ovh/imgs/2021/12/555daf719bb1be25.png)
