### ISSUE TITLE
就没人怀疑这个人是不是朝鲜黑客吗

### ISSUE THREAD

**Issue by NyDubh3** [Liqunkit/LiqunKit_#6]

**Comment by blackjokerzero** [comment]
有啥特征吗

**Comment by NyDubh3** [comment]
> 有啥特征吗

这个人的账户完全是新建的，从来没Star和Fork过任何项目

**Comment by tangxiaofeng7** [comment]
笑出了声

**Comment by zxc12609** [comment]
> > 有啥特征吗
> 
> 这个人的账户完全是新建的，从来没Star和Fork过任何项目

可能是某个大佬的小号啊，这就能断定是后门？

**Comment by Liqunkit** [comment]
我是奥特曼居住在M78星云的光之国,距离地球大约300万光年。

再说朝鲜真的有电脑么？

**Comment by NyDubh3** [comment]
破案了

**Comment by iamsino** [comment]
笑醒了 哈哈哈

**Comment by hilan1** [comment]
破案了，印度黑客

**Comment by TunGuLaMianYG** [comment]
> 破案了，印度黑客

从哪里溯出来是印度黑客的？

**Comment by Liqunkit** [comment]
谢邀，人在国内，刚下飞机，睡醒发现自己成朝鲜/印度人了，在线等，挺急的

**Comment by Blue-01** [comment]
搁着装，不是什么好东西

**Comment by DarkGuard123** [comment]
好家伙  老阴B  别用这个  这家伙 不是印度的就是朝鲜的

**Comment by Liqunkit** [comment]
> 好家伙老阴B别用这家伙不是印度的就是这个朝鲜的

喜欢用就用 不喜欢也没强迫你用 谢谢

**Comment by Zxc123456zxc** [comment]
总有煞笔，自己啥也不懂在这造谣

**Comment by 0xADY** [comment]
Through my manual analysis, I do not think there is a back door
