### ISSUE TITLE
Backdoor??????????????????????????????

### ISSUE THREAD

**Issue by LikNK** [Liqunkit/LiqunKit_#8]
真是个死妈东西你是 加后门的死妈崽

**Comment by Liqunkit** [comment]
你拿出证据？ 张口就来你🈶脸么？

**Comment by strengthenzxy** [comment]
> 真是个死妈东西你是 加后门的死妈崽

还是吃太饱了……

**Comment by LikNK** [comment]
![image](https://user-images.githubusercontent.com/20243850/144155517-184fe9b1-1df2-41bd-a6a9-76a0646eae6b.png)
还要石锤啊

**Comment by LikNK** [comment]
> > 真是个死妈东西你是 加后门的死妈崽
> 
> 还是吃太饱了……

你妈还是死的太少了

**Comment by Dalian000** [comment]
> 真是个死妈东西你是 加后门的死
你用就有用 不用就拉到  嘴巴像长出来样  你多读点书吧

**Comment by LikNK** [comment]
> 安全圈 有你这种败类 真的是很无语

小牛马 你也配安全圈？

**Comment by LikNK** [comment]
> 你拿出证据？ 张口就来你🈶脸么？

气不气啊 牛马东西

**Comment by Dalian000** [comment]
评论关了干嘛？？？玩不起了 ？？出来石锤啊  嘴巴像刚长出来一样

**Comment by LikNK** [comment]
> 评论关了干嘛？？？玩不起了 ？？出来石锤啊 嘴巴像刚长出来一样

删了版本了啊？牛马？

**Comment by LikNK** [comment]
> 评论关了干嘛？？？玩不起了 ？？出来石锤啊 嘴巴像刚长出来一样

谁家的落水狗 气不气啊？

**Comment by Dalian000** [comment]
> 
意思不骂人了

**Comment by Dalian000** [comment]
> 属实是当代窦娥啊

意思不骂人了

**Comment by lrjqaz** [comment]
> > 属实是当代窦娥啊
> 
> 意思不骂人了

不能寒了作者的心

**Comment by Dalian000** [comment]
> > > 属实是当代窦娥啊
> > 
> > 
> > 意思不骂人了
> 
> 不能寒了作者的心

干净给我大哥道歉 还有你骂人的话留在这里删不掉了

**Comment by lrjqaz** [comment]
> > > > 属实是当代窦娥啊
> > > 
> > > 
> > > 意思不骂人了
> > 
> > 
> > 不能寒了作者的心
> 
> 干净给我大哥道歉 还有你骂人的话留在这里删不掉了

雀氏 都是这些人误导了 强烈谴责
